# Generated by Django 2.2.4 on 2019-09-22 05:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_hopplist_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/mnt/D624206F242054B1/Code/Projects/PlayHopp/backend/backend/customers/models.py/media'), upload_to='customer/dp'),
        ),
    ]
