# Generated by Django 2.2.4 on 2019-09-23 02:19

import customers.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/mnt/D624206F242054B1/Code/Projects/PlayHopp/backend/media'), upload_to=customers.models.nameCustomerDP),
        ),
    ]
