# Generated by Django 2.2.4 on 2019-10-04 17:26

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20190923_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[(customers.models.SubscPlanEnum('ONE'), 'ONE'), (customers.models.SubscPlanEnum('THREE'), 'THREE'), (customers.models.SubscPlanEnum('SIX'), 'SIX')], default=customers.models.SubscPlanEnum('ONE'), max_length=20),
        ),
    ]
