# Generated by Django 2.2.4 on 2019-08-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_remove_toy_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='primaryImage',
            field=models.CharField(default='', max_length=800),
        ),
    ]
