# Generated by Django 2.2.4 on 2019-08-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_toy_primaryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
