# Generated by Django 2.2.4 on 2019-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_remove_toy_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='piecesNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='toy',
            name='maxAge',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='toy',
            name='minAge',
            field=models.IntegerField(default=3),
        ),
    ]
