# Generated by Django 2.2.4 on 2019-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_auto_20190915_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
