# Generated by Django 2.2.4 on 2019-09-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_toy_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='piecesNumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
